package sms.gui;

import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import sms.dao.StudentDAO;
import sms.model.Student;
import sms.util.StringUtils;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class MainFrameDesign extends javax.swing.JFrame {
    private DefaultTableModel tableModel;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrameDesign.class.getName());

    /**
     * Creates new form MainFrameDesign
     */
    public MainFrameDesign() {
    initComponents();
    initializeTable();
    loadInitialData();
    addButtonListeners();
}
    
     // Set up table model with proper columns

            private void updateButtonStates() {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

            private void clearFields() {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

        // Load initial data
        refreshTable(StudentDAO.getAllStudents());

        // Setup listeners for buttons and validation
        addButtonListeners();
        setupValidation();

        // Setup menu items (if you have a menu bar)
        setupMenuBar();

        // Initial status
        setStatus("Ready", Color.BLUE);
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        txtMarks = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        cmbCourse = new javax.swing.JComboBox<>();
        btnShowAll = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnStringOps = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Email", "Course", "Marks"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("First Name :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Last Name :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Email :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Course :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Marks :");

        txtEmail.addActionListener(this::txtEmailActionPerformed);

        cmbCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mathematics", "Java OOP", "Networking", "C++", "Interactive web design" }));

        btnShowAll.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnShowAll.setText("Show All");

        btnUpdate.setBackground(new java.awt.Color(51, 51, 255));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setText("Update");

        btnAdd.setBackground(new java.awt.Color(51, 255, 0));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnDelete.setBackground(new java.awt.Color(255, 51, 0));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnStringOps.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStringOps.setText("String Ops");

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setText("Search");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFName)
                            .addComponent(txtMarks, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                            .addComponent(txtLName, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                            .addComponent(cmbCourse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(33, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSearch)
                                .addGap(18, 18, 18)
                                .addComponent(btnShowAll)
                                .addGap(18, 18, 18)
                                .addComponent(btnStringOps)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)
                                .addGap(119, 119, 119)))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete)
                            .addComponent(btnAdd))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnShowAll)
                            .addComponent(btnStringOps)
                            .addComponent(btnSearch))
                        .addGap(24, 24, 24))))
        );

        pack();
    }// </editor-fold>                        

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrameDesign().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JButton btnStringOps;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbCourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtMarks;
    // End of variables declaration                   

     // ==================== LOGIC METHODS ====================
    
    private void initializeTable() {

    String[] columns = {"ID", "First Name", "Last Name", "Email", "Course", "Marks"};

    tableModel = new DefaultTableModel(columns, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    jTable1.setModel(tableModel);

    jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    jTable1.getSelectionModel().addListSelectionListener(e -> {

        if (!e.getValueIsAdjusting()) {

            int row = jTable1.getSelectedRow();

            if (row != -1) {
                txtFName.setText(tableModel.getValueAt(row, 1).toString());
                txtLName.setText(tableModel.getValueAt(row, 2).toString());
                txtEmail.setText(tableModel.getValueAt(row, 3).toString());
                cmbCourse.setSelectedItem(tableModel.getValueAt(row, 4).toString());
                txtMarks.setText(tableModel.getValueAt(row, 5).toString());

                btnUpdate.setEnabled(true);
                btnDelete.setEnabled(true);
            }
        }
    });
}
    
    private void loadInitialData() {
    refreshTable(StudentDAO.getAllStudents());
}

    private void addButtonListeners() {
        btnAdd.addActionListener(e -> addStudent());
        btnUpdate.addActionListener(e -> updateStudent());
        btnDelete.addActionListener(e -> deleteStudent());
        btnSearch.addActionListener(e -> searchStudent());
        btnShowAll.addActionListener(e -> refreshTable(StudentDAO.getAllStudents()));
        btnStringOps.addActionListener(e -> demonstrateStringOps());
    }

    private void setupMenuBar() {
        // If you have a menu bar, add items here.
        // Example (adjust variable names to match your generated ones):
        // JMenuItem exitItem = new JMenuItem("Exit");
        // exitItem.addActionListener(e -> System.exit(0));
        // jMenu1.add(exitItem);
        // ... similarly for Students and Help menus.
    }

    private void addStudent() {
        if (!validateInputs()) return;

        String firstName = (String) txtFName.getText();
        String lastName = (String) txtLName.getText();
        String fullName = StringUtils.toTitleCase(firstName + " " + lastName);
        String email = txtEmail.getText().trim();
        String course = (String) cmbCourse.getSelectedItem();
        double marks = Double.parseDouble(txtMarks.getText().trim());

        Student student = new Student(0, fullName, email, course, marks);
        student.add();
        refreshTable(StudentDAO.getAllStudents());
        clearFields();
        setStatus("Student added successfully.", new Color(0, 128, 0));
    }

    private void updateStudent() {
        int selectedStudentId = 0;
        if (selectedStudentId == -1) {
            JOptionPane.showMessageDialog(this, "Please select a student to update.");
            return;
        }
        if (!validateInputs()) return;

        String firstName = (String) txtFName.getText();
        String lastName = (String) txtLName.getText();
        String fullName = StringUtils.toTitleCase(firstName + " " + lastName);
        String email = txtEmail.getText().trim();
        String course = (String) cmbCourse.getSelectedItem();
        double marks = Double.parseDouble(txtMarks.getText().trim());

        Student student = new Student(selectedStudentId, fullName, email, course, marks);
        student.update();
        refreshTable(StudentDAO.getAllStudents());
        clearFields();
        setStatus("Student updated successfully.", new Color(0, 128, 0));
    }

    private void deleteStudent() {
        int selectedStudentId = 0;
        if (selectedStudentId == -1) {
            JOptionPane.showMessageDialog(this, "Please select a student to delete.");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete this student?",
                "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            Student student = new Student(selectedStudentId, "", "", "", 0);
            student.delete();
            refreshTable(StudentDAO.getAllStudents());
            clearFields();
            setStatus("Student deleted successfully.", Color.RED);
        }
    }

    private void searchStudent() {
        String keyword = JOptionPane.showInputDialog(this, "Enter search keyword (name or email):");
        if (keyword != null && !keyword.trim().isEmpty()) {
            List<Student> results = StudentDAO.searchStudents(keyword.trim());
            refreshTable(results);
            setStatus("Found " + results.size() + " record(s).", Color.BLUE);
        }
    }

    private void refreshTable(List<Student> students) {
        tableModel.setRowCount(0);
        for (Student s : students) {
            // Split full name into first and last for display
            String fullName = s.getName();
            String firstName = fullName;
            String lastName = "";
            int spaceIndex = fullName.indexOf(' ');
            if (spaceIndex != -1) {
                firstName = fullName.substring(0, spaceIndex);
                lastName = fullName.substring(spaceIndex + 1);
            }
            Object[] row = {
                s.getId(),
                firstName,
                lastName,
                s.getEmail(),
                s.getCourse(),
                s.getMarks()
            };
            tableModel.addRow(row);
        }
        clearFields();
    }

    private void clearFields() {
        txtFirstName.setText("");
        txtLastName.setText("");
        txtEmail.setText("");
        txtMarks.setText("");
        cmbCourse.setSelectedIndex(0);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
    }

    private void setupValidation() {
        DocumentListener docListener = new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) { validateInputs(); }
            @Override
            public void removeUpdate(DocumentEvent e) { validateInputs(); }
            @Override
            public void insertUpdate(DocumentEvent e) { validateInputs(); }
        };
        txtFName.getDocument().addDocumentListener(docListener);
        txtLName.getDocument().addDocumentListener(docListener);
        txtEmail.getDocument().addDocumentListener(docListener);
        txtMarks.getDocument().addDocumentListener(docListener);

        cmbCourse.addActionListener(e -> validateInputs());

        // Convert to title case on focus lost (optional)
        txtFirstName.addFocusListener(new FocusAdapter() {
            @Override
            public void focusLost(FocusEvent e) {
                String name = (String) txtFName.getText();
                if (!name.isEmpty()) {
                    txtFName.setText(StringUtils.toTitleCase(name));
                }
            }
        });
        txtLastName.addFocusListener(new FocusAdapter() {
            @Override
            public void focusLost(FocusEvent e) {
                String name = (String) txtLName.getText();
                if (!name.isEmpty()) {
                    txtLastName.setText(StringUtils.toTitleCase(name));
                }
            }
        });

        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
    }

    private boolean validateInputs() {
        String firstName = txtFName.getText().trim();
        String lastName = txtLName.getText().trim();
        String email = txtEmail.getText().trim();
        String marksStr = txtMarks.getText().trim();
        String course = (String) cmbCourse.getSelectedItem();

        boolean valid = true;
        StringBuilder message = new StringBuilder();

        if (firstName.isEmpty() || !firstName.matches("[a-zA-Z]+")) {
            valid = false;
            message.append("First name must contain only letters. ");
        }
        if (lastName.isEmpty() || !lastName.matches("[a-zA-Z]+")) {
            valid = false;
            message.append("Last name must contain only letters. ");
        }

        if (!email.contains("@") || !email.contains(".")) {
            valid = false;
            message.append("Email must be valid (e.g., name@domain.com). ");
        }

        try {
            double marks = Double.parseDouble(marksStr);
            if (marks < 0 || marks > 100) {
                valid = false;
                message.append("Marks must be between 0 and 100. ");
            }
        } catch (NumberFormatException e) {
            valid = false;
            message.append("Marks must be a number. ");
        }

        btnAdd.setEnabled(valid);
        updateButtonStates();

        if (!valid) {
            setStatus(message.toString(), Color.RED);
        } else {
            setStatus("Input valid.", new Color(0, 128, 0));
        }
        return valid;
    }

    private void updateButtonStates() {
        int selectedStudentId = 0;
        boolean rowSelected = (selectedStudentId != -1);
        boolean inputsValid = validateInputs(); // re-evaluate
        btnUpdate.setEnabled(rowSelected && inputsValid);
        btnDelete.setEnabled(rowSelected);
    }

    private void setStatus(String message, Color color) {
        lblStatus.setText(message);
        lblStatus.setForeground(color);
    }

    private void demonstrateStringOps() {
        int selectedStudentId = 0;
        if (selectedStudentId == -1) {
            JOptionPane.showMessageDialog(this, "Please select a student first.");
            return;
        }

        String firstName = txtFName.getText().trim();
        String lastName = txtLName.getText().trim();
        String fullName = firstName + " " + lastName;
        String email = txtEmail.getText().trim();

        // Split (first and last already separate)
        // Substring: email domain
        String domain = "";
        if (email.contains("@")) {
            domain = email.substring(email.indexOf("@") + 1);
        }

        // Concatenate: full name + email
        String nameEmail = fullName + " (" + email + ")";

        // Title case demonstration (already applied on focus lost)
        String titleCaseName = StringUtils.toTitleCase(fullName);

        String result = String.format("""
                                      String Operations on selected student:
                                      Full name: %s
                                      First name: %s
                                      Last name: %s
                                      Email domain (substring): %s
                                      Concatenated: %s
                                      Title case (via StringUtils): %s""",
            fullName, firstName, lastName, domain, nameEmail, titleCaseName
        );

        JOptionPane.showMessageDialog(this, result, "String Manipulation Demo", JOptionPane.INFORMATION_MESSAGE);
    }
}
